services:
  box:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace/hello
    command: /bin/bash
    stdin_open: true
    tty: true
